task :turn_off_alarm do
  puts "Turned off the goddamn alarm"
end

task :groom_self do
  puts "Brushed teeth"
  puts "Showered"
  puts "Waxed moustache"
end

task :make_coffee do
  cups = ENV['COFFEE_CUPS'] || 2
  puts "Made #{ cups } cups of coffee"
end

task :walk_dog do
  puts "Walk the horrible little dog"
end

task :get_ready => [:turn_off_alarm, :groom_self, :make_coffee, :walk_dog] do
  puts "Don't forget your house keys"
end
