namespace :morning do
  desc "Silence the alarm"
  task :turn_off_alarm do
    puts "Turned off the goddamn alarm"
  end

  desc "Conform to society's expectations of beauty"
  task :groom_self do
    puts "Brushed teeth"
    puts "Showered"
    puts "Waxed moustache"
  end

  desc "Make brain better"
  task :make_coffee do
    cups = ENV['COFFEE_CUPS'] || 2
    puts "Made #{ cups } cups of coffee"
  end

  desc "God I hate that dog"
  task :walk_dog do
    puts "Walk the horrible little dog"
  end

  desc "Get ready for an exciting day"
  task :get_ready => [:turn_off_alarm, :groom_self, :make_coffee, :walk_dog] do
    puts "Don't forget your house keys"
  end
end

namespace :morning do
  task :groom_self do
    puts "Blow dry beard"
  end
end

namespace :afternoon do
  desc "Make special afternoon coffee"
  task :make_coffee do
    Rake::Task['morning:make_coffee'].invoke
    puts "Added some bourbon"
    puts "Now ready to face the afternoon"
  end
end

task :default => 'morning:get_ready'
